### ISSUE TITLE
Empty source - Typescript component

### ISSUE THREAD

**Issue by andreoav** [zeplin/cli-connect-react-plugin#20]
I have a TS component that react-docgen playground parses correctly, but when I connect to zeplin it shows the following on Zeplin App.

`< />` 

When I run `zeplin connect` not errors are thrown.

```sh
Zeplin CLI - v1.0.3

Connecting all connected components into Zeplin…
🦄 Components successfully connected to components in Zeplin.
```

**Comment by yuqu** [comment]
Hey, it could have been an issue with the default `react-docgen` resolver. We've recently changed the default resolver and added an option to change into another built-in resolver. You may also enable `react-docgen-typescript` to see if it works for you. Check out README https://github.com/zeplin/cli-connect-react-plugin#using-react-docgen-typescript-for-typescript-components

Closing the issue as it is very stale. I'm truly sorry that we couldn't reply in a timely manner, you can reopen the issue if the problem persists.
