### ISSUE TITLE
"zeplin: command not found" after npm install -g zeplin plugin

### ISSUE THREAD

**Issue by deborah-ufw** [zeplin/cli-connect-react-plugin#23]
Hi everyone, I'm having trouble at every stage of adding Zeplin's Storybook integration to Zeplin.

For this step, I ran `npm install -g @zeplin/cli-connect-react-plugin`. This seemed to go well (and I checked our job board to see if we had an opening for the core.js engineer looking for a good job in the terminal message)

However, `zeplin connect -p @zeplin/cli-connect-react-plugin` returns
`-bash: zeplin: command not found`.

Here's the output.

`$ npm install -g @zeplin/cli-connect-react-plugin
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/@zeplin/cli-connect-react-plugin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ @zeplin/cli-connect-react-plugin@0.2.5
added 122 packages from 157 contributors in 12.383s
ip-192-168-1-82:skipper dspeece$ zeplin connect -p @zeplin/cli-connect-react-plugin
-bash: zeplin: command not found`

I also tried `yarn global add @zeplin/cli-connect-storybook-plugin` since our team mainly uses yarn, but this failed utterly with many complaints about Darwin.

**Comment by yuqu** [comment]
I believe the issue was addressed as mentioned here: https://github.com/zeplin/connected-components-docs/issues/24
