### ISSUE TITLE
Could not find plugin @zeplin/cli-connect-react-plugin failed.

### ISSUE THREAD

**Issue by namuwikilover** [zeplin/cli-connect-react-plugin#28]
ryan@imseonghun-ui-MacBookPro nextunicorn % zeplin connect -p @zeplin/cli-connect-react-plugin          

Error: Cannot find module '@zeplin/cli-connect-react-plugin'
Require stack:
- /Users/ryan/WebstormProjects/nextunicorn/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js
- /Users/ryan/WebstormProjects/nextunicorn/node_modules/@zeplin/cli/dist/src/commands/connect/index.js
- /Users/ryan/WebstormProjects/nextunicorn/node_modules/@zeplin/cli/dist/src/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/ryan/WebstormProjects/nextunicorn/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js:50:65

Connecting components to Zeplin components failed.

    Could not find plugin @zeplin/cli-connect-react-plugin failed.
    Please make sure that it's globally installed and try again.
        npm install -g @zeplin/cli-connect-react-plugin

Hello :)
I don't know why my computer can't find plugin path ㅜㅜ
Can you help me?

**Comment by daartv** [comment]
I'm encountering a similar issue, just checking if this was solved and asking how you managed to fix it
